### ISSUE TITLE
UI not scrolling up to be able to see the promot box at the top

### ISSUE THREAD

**Issue by moeshkeir** [KittyCAD/text-to-cad-ui#122]

**Comment by franknoirot** [comment]
Hi there @moeshkeir, could you give me a bit more detail here?
1. Are you on desktop or mobile? Could you tell me what device you're using?
2. Which page are you on: the main dashboard, or viewing a model?
3. When you say "the promot box", do you mean "the prompt box"?

**Comment by franknoirot** [comment]
I believe this is the same issue spotted by our teammate Ryan, and fixed with #118 with a test
