### ISSUE TITLE
Profile/Avatar breaks in text-to-cad UI (possibly just for accounts without a profile pic?)

### ISSUE THREAD

**Issue by JBEmbedded** [KittyCAD/text-to-cad-ui#81]
When I go from the main site to the UI, the profile photo breaks. Not sure if this is because I don't have a profile pic uploaded to my account, but it happens every time. See pic attached! 
<img width="172" alt="Screenshot 2023-12-23 at 11 22 04 AM" src="https://github.com/KittyCAD/text-to-cad-ui/assets/78819085/cc58ed95-b6a4-4866-a439-c05be080065a">

**Comment by franknoirot** [comment]
Ah interesting I thought Google profiled automatically had Gravatars applied but I bet I just need to provide my own backup

**Comment by franknoirot** [comment]
@JBEmbedded is still seeing this, and I discovered that my assumptions about how to use the `on:error` event on an `img` element were wrong, but I'm in good company as [the Svelte core team didn't see a canonical way to detect img load failure and load a fallback either](https://github.com/sveltejs/kit/issues/8271#issuecomment-1412896334).

I'm going to use Rich's mentioned `naturalHeight` workaround, as 0px x 0px avatar images are going to be a vanishingly small minority of users of text-to-cad-ui.
